services:
    # PHP service
    app:
        build: ./
        container_name: container
        working_dir: /var/
        volumes:
            - ./:/var
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - simple-app-network

    # MySQL database service
    db:
        image: mysql:latest
        container_name: mysql
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./src:/var/www
        env_file:
            - .env
        networks:
            - simple-app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 8006:80
        volumes:
            - ./src:/var/src
            - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - simple-app-network
            
networks:
    simple-app-network:
        driver: bridge
